[project]
name = "llm-explorations"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ell-ai[all]>=0.0.14",
    "ipykernel>=6.29.5",
    "openai>=1.51.2",
    "python-dotenv",
]
